services:
  platform:
    image: stoplight/prism:5
    container_name: dummy-platform
    volumes:
      -  './examples/dummy-platform/platform-api.yaml:/usr/src/prism/platform-api.yaml'
    command: mock -h 0.0.0.0 /usr/src/prism/platform-api.yaml
    expose:
      - '4010'
    restart: unless-stopped
  platform-gateway:
    image: nginx:1.23.3
    container_name: platform-gateway
    hostname: platform-gateway
    volumes:
      - ./examples/platform-gateway/conf.d:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '4010:80'
    restart: unless-stopped
  sample-rp01:
    build:
      context: examples/sample-rp/docker
      args:
        SERVICE_ID: "${RP1_SERVICE_ID}"
        NOTE: "${RP1_NOTE}"
        KEYCLOAK_AUTH_URL: "${AUTH_URL}"
        KEYCLOAK_REALM: "${REALM}"
    container_name: sample-web-app01
    hostname: sample-rp01
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
  sample-rp02:
    build:
      context: examples/sample-rp/docker
      args:
        SERVICE_ID: "${RP2_SERVICE_ID}"
        NOTE: "${RP2_NOTE}"
        KEYCLOAK_AUTH_URL: "${AUTH_URL}"
        KEYCLOAK_REALM: "${REALM}"
    container_name: sample-web-app02
    hostname: sample-rp02
    restart: unless-stopped
    ports:
      - "0.0.0.0:3001:3000"
