name: Run pytest
on: 
  - push
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flask
          pip install authlib
          pip install werkzeug
          pip install requests
          pip install pytest-mock

      - name: PyTest
        run: |
          python -m pytest backend/examples/sample-rp/tests
        continue-on-error: true